### ISSUE TITLE
Absent REMOTE_ADDR in console

### ISSUE THREAD

**Issue by luxemate** [TransactPRO/transactpro-integration-php#45]
[This line](https://github.com/TransactPRO/transactpro-integration-php/blob/master/lib/TransactPRO/Gate/Builders/InitDataBuilder.php#L12) results in PHP notice "Undefined index: REMOTE_ADDR", which is a pain when running scripts from console.

**Comment by pashira** [comment]
Dear Vladislav,
I can offer two solutions for you.

First solution:
Please create pull request here to fix the problem inside the library. 

Second solution:
Please define REMOTE_ADDR inside your file where you use GateClient, example:

<?php
$_SERVER['REMOTE_ADDR'] = "127.0.0.1";

**Comment by luxemate** [comment]
@pashira Hi! Thanks for reply. Messing with globals as well as suppressing notices and warnings is a crutch path, isn't it? :) So I came up with a [pull request](https://github.com/TransactPRO/transactpro-integration-php/pull/46).

**Comment by pashira** [comment]
Thanks for fixing! I am waiting for Travis build https://travis-ci.org/TransactPRO/transactpro-integration-php/builds/193072143 and merge it after.
