### ISSUE TITLE
Outdated version on packagist

### ISSUE THREAD

**Issue by jurchiks** [TransactPRO/transactpro-integration-php#47]
https://packagist.org/packages/transact-pro/gate

Latest stable is listed as 1.0.2, last updated on 2015-04-28.
Is there really no newer stable version? Or is 1.0.2 fine for production use? It's missing recurrent transaction methods though.
There's a lot of dev branches on the main repo for some reason, and very recent commits on master, yet stable is very outdated. Perhaps it is time to tag a new stable version?

**Comment by pashira** [comment]
New version created v1.0.3.
