### ISSUE TITLE
Field 'phone' are mandatory

### ISSUE THREAD

**Issue by luxemate** [TransactPRO/transactpro-integration-php#53]
Hi!

I have a question about this check:
https://github.com/TransactPRO/transactpro-integration-php/blob/03e71de8b56a5200df85c929557b0809f0c6c5ba/lib/TransactPRO/Gate/Builders/InitDataBuilder.php#L43

It prevents omitting the phone number from init request, when the need for that field is determined only by the agreement and can be set not required by the manager. Wouldn't it be better to remove this check?

**Comment by pashira** [comment]
done: https://github.com/TransactPRO/transactpro-integration-php/commit/1f84d875074535aed1e501676e1b588b88e6e0ee

**Comment by luxemate** [comment]
Thank you kindly!
