### ISSUE TITLE
Cannot install latest changes with composer

### ISSUE THREAD

**Issue by luxemate** [TransactPRO/transactpro-integration-php#54]
Even dev-master links to 03e71de8b56a5200df85c929557b0809f0c6c5ba.
Add a new version tag please.

**Comment by pashira** [comment]
New tag was v1.0.8. Doesn't it suite?

**Comment by luxemate** [comment]
For some reason it's not latest: https://i.imgur.com/XLdoXtU.png.
Same is on packagist.org, no v1.0.8 present.

**Comment by pashira** [comment]
Just updated on packagist.org, please check

**Comment by luxemate** [comment]
Got the new version, thanks!
